### ISSUE TITLE
GitHub search page broken

### ISSUE THREAD

**Issue by andycaramba** [Justineo/github-hovercard#10]
Hi. I have broken GitHub search page with enabled Hovercard extension in Chrome.

Without extension
![search react native 2015-12-27 21-35-40](https://cloud.githubusercontent.com/assets/229699/12011087/7a9cca20-ace2-11e5-89a0-ce9ba366d6a2.png)

With extension
![search react native 2015-12-27 21-36-49](https://cloud.githubusercontent.com/assets/229699/12011090/8a236d64-ace2-11e5-9632-722505e66f78.png)

OS: MacOS X 10.11.2
Chrome: Version 49.0.2593.0 dev (64-bit) 
GitHub Hovercard 0.3.3 (last from chrome webstore)

**Comment by Justineo** [comment]
Just confirmed as a bug. I'll fix this in the next version. Thanks for reporting :)
