### ISSUE TITLE
Pull Requests: add name and status of CI jobs

### ISSUE THREAD

**Issue by stlaz** [Justineo/github-hovercard#101]
First of all, a great extension you've got here!

There's one thing I miss in GitHub PR interface that I think might be a nice to have as a feature here. We have a multitude of jobs that are being triggered on every PR. Failure of some may require an immediate action but you always need to click the PR, scroll all the way down and see which jobs are running/failing/succeeding.

It would be very helpful to have the names and statuses of the PR jobs in the hovercard of each PR. Not sure if that's doable, though.

**Comment by Justineo** [comment]
It's technically possible but this requires to load all content for a PR including comments, Git mergeability checks and job status checks, which may cause the loading process very slow for a PR with a lot of discussion.

**Comment by Justineo** [comment]
GitHub API provides a `mergeable` field so that it's trivial to add mergeability check result to hovercards.

**Comment by Justineo** [comment]
PR cards now provide information about reviews and mergeability bu CI jobs are not exposed in GitHub API so this feature might not be implemented here for now. Thanks for the suggestion anyway.
