### ISSUE TITLE
a render problem in the notification page

### ISSUE THREAD

**Issue by GeekaholicLin** [Justineo/github-hovercard#102]
The extension causes wrong  render in notification title which includes HTML tag.

The issue title like `<details> <summary> 語法無法正確 render` can be render correctly in the issue page, but incorrectly in the notification page.

The notification page:

![render](https://user-images.githubusercontent.com/13808849/30321222-eadb45a4-97e7-11e7-8ba1-0524727a7e91.png)

The issue page:

![image](https://user-images.githubusercontent.com/13808849/30410703-5cdc90b0-993f-11e7-94f5-dad7f350d087.png)

After  forbidding the github-hovercard extension:

![image](https://user-images.githubusercontent.com/13808849/30410853-047cc394-9940-11e7-8650-a42d9effb5f0.png)

**Comment by Justineo** [comment]
Thanks for reporting! I'll look into this.

**Comment by Justineo** [comment]
This will be fixed in 1.4.0 soon, thanks!
