### ISSUE TITLE
Stopped working "Connection error"

### ISSUE THREAD

**Issue by futagoza** [Justineo/github-hovercard#105]
GitHub Hovercard seems to have stopped working, outputting the error:
```
⚠️ Connection error

Please try again later.
```
The extension was working fine yesterday, so most likely the recent update caused the error.

I'm using Firefox x64 on Windows 10 Home.

**Comment by Justineo** [comment]
I ported the Firefox version to WebExtensions yesterday. It worked fine when I load it in debug mode and after publishing to AMO it stopped working. I'm still figuring out what caused the problem. Any help will be appreciated.

**Comment by Justineo** [comment]
Oops, I've found the problem here. The build script wrongly packed the Chrome version with inadequate permission in its manifest file for Firefox add-ons. I've republished the add-on.
