### ISSUE TITLE
Hovercard and native tooltip both are visible

### ISSUE THREAD

**Issue by tanmayrajani** [Justineo/github-hovercard#106]
Now that GitHub has introduced native tooltips on links, hovercard and native tooltip both are visible at the same time. They even overlap at few places. Maybe we should somehow disable the native tooltip?

Take a look at this screenshot:

<img src="https://user-images.githubusercontent.com/8295888/31319365-9bbeaab8-ac7f-11e7-8597-42bdb93467ea.png" width="550">

**Comment by Justineo** [comment]
Thanks for reporting! I'll look into this soon.
