### ISSUE TITLE
Safari version is not working

### ISSUE THREAD

**Issue by kamontat** [Justineo/github-hovercard#109]
`no safari extensions certificate`

![screen shot 2017-11-20 at 15 18 05](https://user-images.githubusercontent.com/14089557/33008541-0cf5b5d0-ce06-11e7-9a50-6847c8f80098.png)

**Comment by Justineo** [comment]
It's not an error. The Safari version is no certificated because that requires me to join Apple Developer Program which costs $99/yr.

**Comment by kamontat** [comment]
It's mean safari isn't support anymore right?

**Comment by Justineo** [comment]
“No Safari Extensions Certificate” is just a warning. Do you mean that the extension isn't working in Safari? If so you can just reopen this and I'll look into this later.

**Comment by kamontat** [comment]
yes, I cannot use this extension on my safari

**Comment by Justineo** [comment]
OK. I'll look into this.

**Comment by Justineo** [comment]
`v1.4.4` should be working on Safari. Feel free to reopen this issue if the problem still exists.
