### ISSUE TITLE
Page scrollbar disappears after mouse out

### ISSUE THREAD

**Issue by gluons** [Justineo/github-hovercard#110]
Sometime when I move mouse out from card, the scrollbar of GitHub disappear. I can't scroll page anymore.

I have to move mouse in & out card (many times) to bring it back.

> I found `ghh-noscroll` CSS class in page's `<body>` when my GitHub scrollbar disappear.

**Browser:** Firefox Nightly 59.0a1
**OS:** Linux Mint 18.2 - 64bits

**Comment by Justineo** [comment]
Thanks. That's a known issue and will be fixed in the next version.

**Comment by gluons** [comment]
Oh! This fix has been released. 🎉

![default](https://user-images.githubusercontent.com/4688092/33247870-d1d145d4-d353-11e7-87c5-68798a367b47.png)
