### ISSUE TITLE
Changing Github API token (Chrome)

### ISSUE THREAD

**Issue by Jahhein** [Justineo/github-hovercard#113]
I've looked around in the README and closed issues and I cannot find any information on changing the API token that was assigned to the extension when first prompted for one.

I wanted to follow someone but I didn't have the correct permissions assigned to the previous token. Editing the token for this extension seems to be nearly impossible aside from clearing cookies which I don't want to do. Logging into every site I use is annoying and chrome doesn't allow for pick and choose cookie deleting.

**Comment by Justineo** [comment]
See [FAQ](https://github.com/Justineo/github-hovercard/blob/master/README.md#faq):

> **Triple click** on any hovercard and the access token form will pop out.

**Comment by Jahhein** [comment]
Thank you. I dont know how I missed that. :(

I apologize.

**Comment by Justineo** [comment]
It's okay :)
