### ISSUE TITLE
Optionally Disable GitHub User Hover

### ISSUE THREAD

**Issue by Riajyuu** [Justineo/github-hovercard#119]
![image](https://user-images.githubusercontent.com/16912240/37865028-ad69852a-2fb1-11e8-9016-1449e559132a.png)

Two hover cards shown up together seems really strange

**Comment by Justineo** [comment]
GitHub delivered this user hovercard feature like yesterday or the day before. I'll fix this later maybe by disabling the native hovercard but extract the additional contextual information there into the extension's hovercard. I've been busy this week so I'll have to fix this after a week or two.
