### ISSUE TITLE
Unable to add GitHub Enterprise domain

### ISSUE THREAD

**Issue by jachstet-sea** [Justineo/github-hovercard#120]
Hi and thanks for this nice Extension. While it worked in the past, it is somehow no longer working with our GitHub Enterprise instance. When I try to add the URL in the Addon's settings, it reports "Domain permission denied." after clicking the "Save" button. I also don't see a way to grant the Addon that permission.
Any ideas?

Update: Forgot: Fireox 59.0.2, github-hovercard 1.4.5

**Comment by Justineo** [comment]
I'll look into this in a few days, thanks for reporting.

**Comment by jachstet-sea** [comment]
Same problem with v1.5.1

**Comment by brijeshsch** [comment]
hi @Justineo any tentative date this could be resolved on the enterprise edition? Thanks

**Comment by brijeshsch** [comment]
Thanks it works fine.

**Comment by jachstet-sea** [comment]
Agreed, I just updated to v1.6.0 and the issue is fixed! Thanks!
