### ISSUE TITLE
Extension slows down firefox quantum

### ISSUE THREAD

**Issue by xahon** [Justineo/github-hovercard#121]
I'm using Ubuntu 18.04 and Firefox quantum 60.0.1  

When I'm researching PRs page a message popup appears at the top of the viewport  

![image](https://user-images.githubusercontent.com/18731681/40897923-57b07ffc-6801-11e8-9f56-6f3b7b3fcd58.png)  

And it really makes it very slow. When disabling the extension this page is loading faster

**Comment by gluons** [comment]
Similar to #107.

I also face this issue sometime now. Seems this issue is back.

**Comment by Justineo** [comment]
@gluons Can you provide a real reproducible URL? Thanks!

**Comment by gluons** [comment]
@Justineo It's randomly happen. OK. If I see this message again, I'll put it here.

@xahon If you face that warning again, please put the URL here.

**Comment by talha131** [comment]
@Justineo I have been noticing this issue in FF Dev Edition for few months now. 

It almost always happen in project page of a private repo, size of which is around 7.5 GB. I haven't noticed this issue, in public repos or non-project pages so far.

It could be my observation is biased b/c I spent most of my time in the said private repository.

**Comment by gluons** [comment]
OK. I just see this message again on https://github.com/facebook/react-native/issues/14209

**Comment by DogChan** [comment]
@Justineo this issue has been happening randomly to me, it is hard to navigate through GitHub because of it, my browser usually will give me the message GitHub Hovercard is causing Firefox to slow down, I think something in this extension is running in the background that might be using a lot of memory or fetching some web data, making the browser slow down.

**Comment by Justineo** [comment]
@DogChan Can you provide an actual URL for me to look into? The slow down is more likely to be caused by those page with a lot of content.

**Comment by DogChan** [comment]
@Justineo It happened to me three times in this one, https://github.com/30-seconds/30-seconds-of-code/blob/master/yarn.lock you should try to set some kind of limit, so the extension will stop trying to fetch data on links that you are not going to use, or are not currently using.

**Comment by DogChan** [comment]
@Justineo It happened to me three times in this one, https://github.com/30-seconds/30-seconds-of-code/blob/master/yarn.lock you should try to set some kind of limit, so the extension will stop trying to fetch data on links that you are not going to use, or are not currently using.

**Comment by kroppt** [comment]
It appears to me that the browser is just waiting on the extension when you try navigating to a new page. Perhaps if fetching could be cancelled upon navigation, that would limit the navigation delay.

**Comment by darkred** [comment]
I have noticed in both Firefox 67/Chrome 74 (win 10) that with the extension enabled, 
trying to type anything in a searchbox, makes the browser become painfully slow.

STR
- in a fresh Firefox/Chrome profile with only GitHub Hovercard 1.8.0 + Tampermonkey 4.8.41 with the following userscript: [GitHub Search Autocomplete](https://greasyfork.org/en/scripts/28592-github-search-autocomplete)
- open e.g. https://github.com/Justineo/github-hovercard/issues
- click inside either the top 'Search or jump to' searchbox or the Issues searchbox 
and try to type anything: the characters are displayed very slowly, and especially Firefox shows `A script in this extension is causing Firefox to slow down”`.
- Also, try to select your typed word via doubleclick: the word will become selected after 8 sec in my system!!
- Disabling GitHub Hovercard fixes the issue.

PS. Kindly cc'ing @Mottie, author of the aforementioned userscript.

**Comment by fregante** [comment]
> It appears to me that the browser is just waiting on the extension when you try navigating to a new page.

If that's the case, I think it's caused by https://github.com/Justineo/github-hovercard/blob/beb1257d741b1c7e651a870faebcf9796420aeb6/extensions/chrome/background.js

And can be solved by using this solution instead: https://github.com/fregante/webext-dynamic-content-scripts/blob/master/how-to-add-github-enterprise-support-to-web-extensions.md

**Comment by strugee** [comment]
Thank you for your hard work, @Justineo! I for one really appreciate this extension and I'm excited this bug is fixed 🎉

**Comment by micgro42** [comment]
Oh, I uninstalled this extension because that error was so annoying. I reinstalled it just now :). Thank you for your work!
