### ISSUE TITLE
Positionning is frustrating

### ISSUE THREAD

**Issue by tristanbes** [Justineo/github-hovercard#125]
Hello,

Can you change the position of the tooltip to the Right ?
Or at least provide an option to do so ? 

Right now it's frustrating because the tooltip hides so much information on Github when it appears, and then you have to mouve out with your mouse, then go back down to continue navigating.

It wouldn't be an issue if the tooltip opens on the right instead of top/bottom.

**Comment by tristanbes** [comment]
I think it's not the delay, it's about closing the tooltip.
I hover a link, read the tooltip, then instead of just slightly move my cursor up or down to read the next tooltip content, I have to move outside, then replace my mouse cursor to the next element.

It's hard to explain, but do you get my point ?

**Comment by Justineo** [comment]
I got your point. I think the problem occurs when you want to quickly inspect throughout a list of repos or something.

**Comment by Justineo** [comment]
Supported via a placement option in v1.6.1.
