### ISSUE TITLE
The horizontal scrollbar of the code block  overflows out of the readme of the card

### ISSUE THREAD

**Issue by linqiang007** [Justineo/github-hovercard#128]
for image

![overflow](https://user-images.githubusercontent.com/12245095/57191366-3eebf600-6f57-11e9-8bd6-ad60383ad68f.png)

**Comment by Justineo** [comment]
Do you have stable reproduction of this? I'm not able to reproduce this.

**Comment by linqiang007** [comment]
@Justineo you should scroll it, like this.
 [ink-text-animation](https://github.com/yardnsm/ink-text-animation)
<img src="https://user-images.githubusercontent.com/12245095/57191643-75774000-6f5a-11e9-945d-b45df492d8c3.png" width="400" />

**Comment by Justineo** [comment]
Still not able to reproduce. And honestly I don't think it's a bug of this project (there's no way for developers to place scrollbar at that location) and there's probably something wrong with the browser.
