### ISSUE TITLE
Possible bug : Hovercard is overriding / disabling Stylus themes

### ISSUE THREAD

**Issue by MostHated** [Justineo/github-hovercard#130]
Hello,
    I was checking the settings out because [I use Stylus](https://github.com/openstyles/stylus) and [this Github Dark Theme](https://github.com/StylishThemes/GitHub-Dark) and my hovercards were always white so I thought I would tinker a bit, but as soon as I clicked on the settings in Hovercard Stylus disabled and my theme no longer worked. I disabled Hovercard and then my theme came back. I checked again to make sure and sure enough it happened again. If therecould be a way to completely disable any sort of styling, that would be great.

Thanks,
-MH

**Comment by Justineo** [comment]
You can choose the dark theme in extension options.

**Comment by MostHated** [comment]
Yes, when I do that, it disables my other plugin Stylus. What I am saying is, the style settings of Hovercard make my other addon Stylus not work. I have to disable Hovercard for my style that I actually want to use to come back.
