### ISSUE TITLE
Please add a dark theme

### ISSUE THREAD

**Issue by Naatan** [Justineo/github-hovercard#132]
Dark mode is becoming more common every day, I try to use dark mode for everything. Sadly this extension is a big eyesore at the moment because it generates blinding white squares. Dark theme would be much appreciated!

**Comment by Justineo** [comment]
Have you tried the classic theme in the extension options?

**Comment by Naatan** [comment]
Ahh very nice, thank you! I missed it because when I click "Extension Options" on the extension page (in Opera) nothing happens, so I assumed it didn't have any options.

If I access options via the addon button in the toolbar it works though!

**Comment by Naatan** [comment]
Hmm it seems this themeing is a little bugged. It works on some hovers but not others, also when I switch or refresh a page it may or may not work for the same ones that it did previously.

Restarted my browser and cleared cache, behaviour stays the same.

**Comment by Geeyun-JY3** [comment]
@Naatan Try [GitHub Dark](https://github.com/StylishThemes/GitHub-Dark). It [supports](https://github.com/StylishThemes/GitHub-Dark#supported-github-extensions) GitHub Hovercard.

**Comment by Technetium1** [comment]
This seems to be working very well with the new Dark mode. Would be nice if it were less translucent though... https://github.blog/changelog/2020-12-08-dark-mode-public-beta/

**Comment by Justineo** [comment]
See #158.
