### ISSUE TITLE
[bug] cpu usage up to 100% when switch between some page

### ISSUE THREAD

**Issue by Cologler** [Justineo/github-hovercard#133]
steps:

1. open https://github.com/MicrosoftDocs/Console-Docs/tree/master/docs
1. click file `TOC.md`

**Comment by ForsakenHarmony** [comment]
https://github.com/ChrisRM/material-theme-jetbrains/compare/v4.0.5...master

another example

**Comment by scott-ho** [comment]
same here, it has severe performance issue on large files comparison page.

**Comment by ForsakenHarmony** [comment]
I've disabled the extension for now

**Comment by maple3142** [comment]
Same, it will freeze my browser on some big source file such as https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/volume/persistentvolume/pv_controller.go

**Comment by cpriest** [comment]
Same here, love the extension, but can't deal with the enormous performance issues.

**Comment by niladam** [comment]
Actually, upon having a look at the files changed in a PR i get a huge CPU usage. For now, i've disabled this.

I am using the 1.8.0 version.

**Comment by niladam** [comment]
@Justineo - sorry for posting this right after my previous comment, but i think a really good option to prevent this would be to somehow allow some sort of exceptions where the extension shouldn't be activated automatically.

**Comment by nmai** [comment]
Can anyone chime in here and note whether they had the Refined Github extension installed at the time?

**Comment by ForsakenHarmony** [comment]
Yes, have it installed (for other people, use reactions instead of posting comments)

**Comment by nmai** [comment]
In that case I believe this is related to the issue I filed the other day- #140 
My (admittedly unscientific) testing showed that heavy performance issues appeared on some pages while Hovercard+Refined were installed, but things were fine when only one or the other was installed. Would be great if someone else could confirm that.

So far though it seems like Hovercard + Refined just don't play well together 😢

**Comment by cpriest** [comment]
Yeah, I ended up uninstalling it unfortunately.  I really liked it
