### ISSUE TITLE
Cross Site Scripting

### ISSUE THREAD

**Issue by atoooooooooom10** [Justineo/github-hovercard#14]
“><script>alert(document.cookie)</script>

Just hover your mouse to my issue and XSS will pop out.

<img src="http://i.imgur.com/mTle1hI.png" />

**Comment by Justineo** [comment]
Thanks for reporting. This should be fixed asap.

**Comment by atoooooooooom10** [comment]
Happy to help.

**Comment by Justineo** [comment]
Added XSS filtering using [js-xss](https://github.com/leizongmin/js-xss). Can't do HTML encode for issue body because it's Markdown (which may contain HTML tags).
