### ISSUE TITLE
Huge slowdown / page freeze when viewing large diffs in PR (Conflict w/ Refined GH ext)

### ISSUE THREAD

**Issue by nmai** [Justineo/github-hovercard#140]
Attempting to expand a diff with 830 changes appears to work fine until you attempt to scroll down- the page seems to truncate and end in whiteness and at that point scroll gets stuck and you cannot do anything on the page for 5-30s. Eventually the rest of the content loads up and behavior returns to normal.

Disabling hovercard extension and attempting to expand+view the diff again works as expected, perfectly acceptable performance on expand and scroll.

*edit*: Initially I had been blaming content.js before I realized it was never a dependency of this repo. The Refined Github extension uses it. Further testing on the 830 line diff reveals:
- Hovercard enabled alone causes **no noticeable performance hit**
- Refined Github enabled alone causes a **very slight performance hit**
- Both of them enabled together causes a **huge performance hit**. system CPU consumption jumps from 5% to 30-40% sustained, so likely 100% consumption of a single core.

So it's likely this is a conflict between the two extensions and how they listen for and process new content. I am really not sure if there is anything actionable here as neither extension's maintainers are responsible for the others, but Hovercard+Refined are two popular and no-brainer installs for anyone looking to augment the GH experience so I feel like this conflict may affect many whether they realize it or not. 

Chrome 79.0.3945.117 (current)

**Comment by vjpr** [comment]
Yep saw this when scrolling in big diff in the Chrome Performance profile.

**Comment by loilo** [comment]
Same when used together with the [GitHub Issue Link extension](https://github.com/bfred-it/github-issue-link-status) on pages with a lot of issue/PR links (such as the [TypeScript roadmap](https://github.com/microsoft/TypeScript/wiki/Roadmap)). Looks like the Hovercard extensions goes nuts when it has to "share" elements (like links) with another extension.

I'll attach the performance profile of a page load with both extensions activated:
[GitHub-Hovercard-Profile.json.zip](https://github.com/Justineo/github-hovercard/files/4628134/GitHub-Hovercard-Profile.json.zip)

**Comment by fregante** [comment]
> I'll attach the performance profile of a page load with both extensions activated:

Thanks, very useful. It looks like it's getting stuck in the MutationObserver calling `extract` dozens of times:

https://github.com/Justineo/github-hovercard/blob/beb1257d741b1c7e651a870faebcf9796420aeb6/src/hovercard.js#L32-L39

I think it would be more efficient to have a single `extract` call in the observer’s callback, especially because I think the `target` never changes since there's only one element `observe`d
```diff
  let observer = new MutationObserver(mutations => {
    if (isExtracting) {
      return
    }

+   let target = mutation[0].target
+   if (!isExclude(target)) {
+     extract(target)
+   }
-   mutations.forEach(mutation => {
-     if (mutation.type === 'childList') {
-       let target = mutation.target
-       if (!isExclude(target)) {
-         extract(target)
-       }
-     }
-   })
  })
```

**Comment by loilo** [comment]
Yep, that's what I'd seen as well. However, doesn't look like there will be PRs accepted here anytime soon. 🙁 

I had also solved this in a local fork of `github-issue-link-status` by wrapping [the class-adding code](https://github.com/loilo/github-issue-link-status/blob/master/source/github-issue-link-status.js#L124-L127) in a `requestAnimationFrame`. It works (not sure why, haven't taken a closer look), but of course that's more of a hack and not the proper place to fix this.

**Comment by Spurlos** [comment]
So, I have stumbled upon the same issue. Seems that this extensions is abandoned by its author. @Justineo can you please confirm if your are still willing to support this project?
