### ISSUE TITLE
Connection Error 

### ISSUE THREAD

**Issue by saeedhassansolangi** [Justineo/github-hovercard#144]
![connection-error](https://user-images.githubusercontent.com/45068032/80133953-782dd380-85b7-11ea-986f-018217dc2129.png)

first it was working fine but now  I am Getting This Error 

and i am using ubantu and chrome browser

**Comment by manohar-voggu** [comment]
Same, on Mac OS Catalina + Chrome Version 81.0.4044.129 (Official Build) (64-bit)
![Screenshot 2020-05-06 at 8 49 05 AM](https://user-images.githubusercontent.com/50870617/81135631-98c23a00-8f76-11ea-987c-4e5c9f5d5081.png)

**Comment by manohar-voggu** [comment]
@saeedhassansolangi did u add a GitHub Access Token to the extension?

**Comment by Justineo** [comment]
Did you add an access token which is not expired?

**Comment by manohar-voggu** [comment]
@saeedhassansolangi it's because of Github Api rate limit.

> GitHub limits unauthenticated API requests to 60 per hour but after binding your access token you will be able to enjoy the rate limit of 5,000 requests per hour.
> 
> Triple click on any hovercard and the access token form will pop out.
> 
> You should at lease add permission for public_repo to enable star/unstar, and user:follow to enable follow/unfollow.
> 

I had this same error and solved it by adding a Github personal access token to the extension with said permissions

**Comment by saeedhassansolangi** [comment]
@Justineo Yes, My __access token__ was expired after adding new access token it is working now .

**Comment by saeedhassansolangi** [comment]
Thankyou @manohar-voggu for your reply . I have solved the issue with your guidance.
