### ISSUE TITLE
Sponsor URLs should be ignored

### ISSUE THREAD

**Issue by chrismessina** [Justineo/github-hovercard#149]
![image](https://user-images.githubusercontent.com/22610/92337547-55302780-f05f-11ea-94e8-6ebd42d5d255.png)

Hover over the "say thanks" button on [this page](https://github.com/nikitavoloboev/alfred-my-mind), which links here:

https://github.com/sponsors/nikitavoloboev

Either a fancy Sponsor hovercard should be displayed, or it should be ignored.

**Comment by Justineo** [comment]
Fixed in v1.9.0.
