### ISSUE TITLE
编辑历史中显示超链接更改内容的 tooltip 不会弹出

### ISSUE THREAD

**Issue by Geeyun-JY3** [Justineo/github-hovercard#150]
编辑历史涉及一个会弹出 GitHub Hovercard 的超链接的更改时，鼠标悬停在该超链接上时显示超链接更改内容的 tooltip 不会弹出。这种情况是不是应该针对优化一下？

未开启 GitHub Hovercard 时：
![image](https://user-images.githubusercontent.com/49396421/95882944-e015e780-0dac-11eb-9820-94e7279e1387.png)
开启 GitHub Hovercard 后：
![image](https://user-images.githubusercontent.com/49396421/95874520-8b21a380-0da3-11eb-9f04-61c35ac06084.png)

具体例子可以查看我这条 [issue](https://github.com/openstyles/stylus/issues/1045#issue-710264953)，就最近的一次编辑历史。

**Comment by Justineo** [comment]
目测这是其他扩展提供的功能，很遗憾要兼容所有扩展的行为这是无法保证的。

**Comment by Geeyun-JY3** [comment]
啊这不是 GitHub 官方的功能吗？
![image](https://user-images.githubusercontent.com/49396421/95947482-49374280-0e21-11eb-8eea-e25658b8fe01.png)

**Comment by Justineo** [comment]
抱歉，我看漏了，没看到是编辑记录里面的。感觉这里应该忽略掉 commit 卡片比较好，还是显示内容变动。

**Comment by Geeyun-JY3** [comment]
> 感觉这里应该忽略掉 commit 卡片比较好，还是显示内容变动。

同意

**Comment by Geeyun-JY3** [comment]
我觉得可以参考 GitHub 官方加个 [快捷键](https://docs.github.com/en/free-pro-team@latest/github/getting-started-with-github/keyboard-shortcuts#site-wide-shortcuts)，当焦点在和 hovercard 上时，按 <kbd>esc</kbd> 键可关闭 hovercard 并重新聚焦在光标上。
