### ISSUE TITLE
hovercard on unknown avatar

### ISSUE THREAD

**Issue by tinect** [Justineo/github-hovercard#151]
If the avatar is unknown it doesn't have an url (not in an a-tag).
But this plugin tries to load it.
![image](https://user-images.githubusercontent.com/135993/96702986-9ae84b80-1392-11eb-937b-9438a822834d.png)

The selector should be restricted to parent a-tag for `avatar`

**Comment by pxldevv** [comment]
Probably same thing here

![image](https://user-images.githubusercontent.com/61668117/219491801-562772e4-214a-414b-af38-72b30c4d698f.png)
