### ISSUE TITLE
New GitHub Dark Theme

### ISSUE THREAD

**Issue by vincentscode** [Justineo/github-hovercard#158]
With the new GitHub dark theme the current theme of GitHub Hovercard sadly does not fit in with the UI anymore.
Would it be possible to add a fitting theme?
![Screenshot 2020-12-12 205342](https://user-images.githubusercontent.com/26576880/101993594-28258d80-3cbc-11eb-9220-ec75565f73cd.png)

**Comment by aaznadi** [comment]
+1

**Comment by Justineo** [comment]
There is a built-in classic theme which is dark but not dedicated for GitHub’s new dark mode. You can try switch to it by changing the extension options.

**Comment by aaznadi** [comment]
@Justineo but it looks very nasty.
<img width="703" alt="screenshot" src="https://user-images.githubusercontent.com/71615388/103126408-79575900-468e-11eb-9d08-684b1224e7f1.png">

**Comment by TreyRuffy** [comment]
I have added it in #160

**Comment by Justineo** [comment]
Thanks to @TreyRuffy we now have two extra themes, both work for GitHub's dark mode!
