### ISSUE TITLE
Conflict with 'Refined GitHub' extension: its `user-local-time` feature

### ISSUE THREAD

**Issue by darkred** [Justineo/github-hovercard#162]
I have noticed that, if you have enabled both GitHub Hovercard (GH) and Refined GitHub (RG),
the `user-local-time` RG feature ([screenshot](https://user-images.githubusercontent.com/1402241/69863648-ef449180-12cf-11ea-8f36-7c92fc487f31.gif)) becomes broken.

STR

- In a fresh Chrome 87/Firefox 84 (win 10) install latest GitHub Hovercard 1.9.2 and Refined Github 21.1.10 extensions
- login to GitHub with your credentials and generate + enter a token for each extension
- disable GH and visit any issue or PR page e.g. https://github.com/sindresorhus/refined-github/pull/3886
- hover mouse over over e.g. the `fregante`'s avatar:
![2021-01-14_000208](https://user-images.githubusercontent.com/723651/104515646-c9756b80-55fb-11eb-9d86-9a0f029cb5d6.jpg)
- now enable GH and hover mouse again (below are screenshots with the two extension styles) :
 
  <details>
  <summary>GitHub (Light)</summary>
  
  ![2021-01-14_000040](https://user-images.githubusercontent.com/723651/104515508-96cb7300-55fb-11eb-9eec-f95d7a877a31.jpg)
  </details>

  <details>
  <summary>Classic (Dark)</summary>

  ![2021-01-14_000004](https://user-images.githubusercontent.com/723651/104515519-9b902700-55fb-11eb-9885-cf188a239c0c.jpg)
  </details>

  There's no error in Console.

**Comment by Justineo** [comment]
The estimated local time of a user isn't provided by GitHub's API and Refined GitHub supports it by modifying GitHub's own hovercard, which is replaced by GitHub Hovercard's implementation (as you can see they are a bit different, like stats for followers/following/repos, follow/unfollow button, etc.). I don't think I'll fix this unless we can work out a "protocol" to share data across extensions.

**Comment by darkred** [comment]
Ok, thank you for your response.

**Comment by darkred** [comment]
> I don't think I'll fix this unless we can work out a "protocal" to share data across extensions.

Kindly cc'ing @fregante (because I missed that when I wrote the OP) in case he'd like to share his opinion on this.
