### ISSUE TITLE
trending页的下拉列表失效？

### ISSUE THREAD

**Issue by waldens** [Justineo/github-hovercard#17]
我这边，Firefox43.02 + Userscript脚本方式
会造成<https://github.com/trending>，这个页面的这俩按钮失效。如图
只有我这样吗？

PS：发这个issue时，又发现，编辑框的Preview也不能点按了

![](http://ww1.sinaimg.cn/large/d80a8e60gw1f0hh96u3m6j20dw09274w.jpg)

**Comment by Justineo** [comment]
Userscript 版本引入的 jQuery 和 GitHub 自带的冲突了（插件版运行环境是隔离的），我修复一下。
