### ISSUE TITLE
Adjust settings when installed via UserScript [ViolentMonkey - Firefox]

### ISSUE THREAD

**Issue by MostHated** [Justineo/github-hovercard#170]
Hey there,
    I have never tried to adjust something installed via ViolentMonkey on Firefox, are there settings like there are in the extensions? For some reason, the theme coloring of my hovercards became white today, but I am not sure the name I should be looking for within the userscript itself to try and change it back, and I don't see any sort of relevant settings in the ViolentMonkey UI. Does anyone happen to have any ideas?

Thanks,
-MH

**Comment by MostHated** [comment]
Now that I look, it looks like I manually edited some of the colors manually and saved them in Stylus, so I am guessing something must have changed on githubs side for it to have changed the colors. Though, it would be good to know if settings exist and can be adjusted either way.

**Comment by Justineo** [comment]
We do currently not support settings for the UserScript version. We do support switching themes for browser extensions.

**Comment by alexocode** [comment]
I'd like to revive this issue, given that the extension isn't available for Firefox anymore.
