### ISSUE TITLE
octicons.woff is being loaded even though it's not needed

### ISSUE THREAD

**Issue by OmgImAlexis** [Justineo/github-hovercard#19]
If I enable this extension and check Chrome's console I get warnings that `/octicons.woff` is trying to be loaded but can't since it violates the CSP rules Github has enabled. Since it never loads I'm assuming it's not actually needed. I tried searching through the project but can't seem to find where it actually attempts to load the file.

**Comment by Justineo** [comment]
Hi. Thanks for reporting.

Octicons are no longer loaded as icon font in GitHub and GitHub Hovercard has switched to use SVG icons in the latest version so you can't find the piece of code which loads the font files now.
