### ISSUE TITLE
API limit exceeded

### ISSUE THREAD

**Issue by TheInitializer** [Justineo/github-hovercard#20]

**Comment by Justineo** [comment]
Did the card suggest you to create and bind an access token to avoid this?

**Comment by TheInitializer** [comment]
Yes, I created it and now don't know what to do with it

**Comment by Justineo** [comment]
There should be a popup form to fill in the token you just created on the GitHub page you were visiting. Did you see it?

**Comment by TheInitializer** [comment]
No

**Comment by TheInitializer** [comment]
It just showed the little message

**Comment by Justineo** [comment]
Okay I see it should be fixed in `v0.4.1`. Tell me if it works please :)

**Comment by Justineo** [comment]
Sorry I'm now able to reproduce the problem right now. Does this happen all the time? And which version(Chrome/Firefox/Opera/..., version number) are you using? Does it happen on all cards (user/repo/issue)? Thanks :)

**Comment by TheInitializer** [comment]
Firefox Developer Edition 47.0a2. It hasn't happened in a while, mostly because I try to not use it excessively, and when it does happen, it happens on every card.

**Comment by Justineo** [comment]
@TheInitializer Thanks for the info. I'll look into this.

**Comment by Justineo** [comment]
@TheInitializer Hi, I made some updates on API requests. Because I wasn't able to reproduce your problem so I'm just hoping that it's fixed in the latest version.

**Comment by marktopper** [comment]
The popup does not show the actual form for inputting the API token generated.
![screen shot 2016-04-06 at 14 39 11](https://cloud.githubusercontent.com/assets/2232539/14316820/6e61692e-fc05-11e5-9bee-59737a620662.png)

**Comment by Justineo** [comment]
@marktopper Did it show after you clicked the "Create a new access token" link?

**Comment by marktopper** [comment]
@Justineo, will check it out.

**Comment by marktopper** [comment]
I can confirm that you are right @Justineo.

![screen shot 2016-04-07 at 09 24 25](https://cloud.githubusercontent.com/assets/2232539/14343640/9e2884ec-fca2-11e5-8a9c-d519fcc1e1d9.png)

**Comment by Justineo** [comment]
Closing this now. Feel free to reopen if it still occurs.
