### ISSUE TITLE
Popup position is not right on smooth zoomed page on OS X

### ISSUE THREAD

**Issue by chuanconggao** [Justineo/github-hovercard#22]
The popup position is not right on OS X, if zoomed by pinch-and-zoom with two fingers on trackpad.

**Comment by Justineo** [comment]
It's a problem of Tooltipster. I've reported an issue there: https://github.com/iamceege/tooltipster/issues/541

**Comment by Justineo** [comment]
This issue won't be fixed in this project so I'm closing this for now.
