### ISSUE TITLE
Delayed appearance of hover-cards?

### ISSUE THREAD

**Issue by devkhan** [Justineo/github-hovercard#23]
Right now the hover cards appear immediately on hover over a link. An option to delay the appearance of the cards will be useful like in Facebook.

I can try to implement it if there is a demand.

**Comment by Justineo** [comment]
This may be helpful for some people. I can ship this feature in the next release.

**Comment by Justineo** [comment]
The feature will be implemented for browser extension versions in `v0.5.0`. Publishing soon.
