### ISSUE TITLE
Immediately reset timeout on mouseout/mouseleave

### ISSUE THREAD

**Issue by edjroot** [Justineo/github-hovercard#24]
First of all, great extension! :)

I noticed that the timeout isn't immediately reset when the mouse cursor leaves links (and I think it should). As an example, you can set the delay to, say, 2000 ms, go to your profile page and wildly move the cursor over your repos. After enough time, at least one hovercard will appear. While wildly moving your cursor isn't a very common thing to do, this still happens often enough to be noticed while I'm browsing some pages.

Regardless of this bug (or feature?), I'd like to leave a suggestion for further improvement: What about using something like [hoverIntent](http://cherne.net/brian/resources/jquery.hoverIntent.html) instead of plain delays? It triggers many fewer "false positives".

Thanks for your attention!

**Comment by Justineo** [comment]
At the moment I'm using a dev version of Tooltipster to generate popup tooltips and `delay` is actually handled there. Maybe I'll try a later version sometime but I don't think I'll fix this problem in this project.

**Comment by edjroot** [comment]
Ok, no problems. Mind a pull request (as long as I have the time to do it)?

**Comment by Justineo** [comment]
Won't fix in this project.
