### ISSUE TITLE
hovercard is not working anymore

### ISSUE THREAD

**Issue by alexfalcucc** [Justineo/github-hovercard#25]
trying to load the card and get this when always load the github page:
![hovercard](https://cloud.githubusercontent.com/assets/6964211/15379828/3cde1218-1d47-11e6-9552-ee7152453909.png)

note: it's strange because when I go to your [github.io](https://justineo.github.io/github-hovercard/) page, it works fine.

**Comment by Justineo** [comment]
I cannot reproduce your problem on my laptop. Could you please provide the extension version / browser version so that I can look into this?

**Comment by alexfalcucc** [comment]
yeah, here's both:

Google Chrome 50.0.2661.102
GitHub Hovercard 0.5.0

**Comment by alexfalcucc** [comment]
closing this issue.

I've just reinstalled Google Chrome and it works! 

thank you

**Comment by Justineo** [comment]
OK.
