### ISSUE TITLE
UI bug is glitching

### ISSUE THREAD

**Issue by codynguyen1116** [Justineo/github-hovercard#26]
Not sure how to describe it, so I'll give a screenshot: I'm using Chrome 50.0.2661.102 on Windows 10.

![image](https://cloud.githubusercontent.com/assets/4723983/15594637/0491cdbe-237d-11e6-839d-ce66b38b1aad.png)

**Comment by Justineo** [comment]
Thanks for reporting! I'm able to reproduce this problem and will look into this.

**Comment by Justineo** [comment]
Oops, it seems that GitHub has updated it's styles which contain some naming conflicts with my extension.

**Comment by Justineo** [comment]
@codynguyen1116 The problem is now fixed in the latest version :)

**Comment by codynguyen1116** [comment]
@Justineo thanks :D
