### ISSUE TITLE
Hovercard styling issue

### ISSUE THREAD

**Issue by julmot** [Justineo/github-hovercard#27]
For me it's broken since today:

![hover-issue](https://cloud.githubusercontent.com/assets/8310677/15607578/3f190f32-2414-11e6-8eec-c8034d06784b.png)

Browser : FF 48.0a2

**Comment by Justineo** [comment]
See #26. The fix version of Firefox is currently under review  and did not published yet .

**Comment by Justineo** [comment]
GitHub Hovercard Firefox add-on v0.6.3 is public now.
