### ISSUE TITLE
Broken UI

### ISSUE THREAD

**Issue by fayimora** [Justineo/github-hovercard#29]
I noticed a day or two ago, the UI was broken. Any idea why? 

<img width="520" alt="screenshot 2016-05-29 09 17 49" src="https://cloud.githubusercontent.com/assets/648684/15632056/643921d8-257e-11e6-906a-2b662e5936b9.png">

**Comment by Justineo** [comment]
See #27. Please update to latest version and try again. :)

**Comment by fayimora** [comment]
Oops, I should have looked at closed issues. Couldn't figure out how to update though so I just deleted and re-installed.
