### ISSUE TITLE
Hovercard tooltip issue

### ISSUE THREAD

**Issue by julmot** [Justineo/github-hovercard#30]
![issue](https://cloud.githubusercontent.com/assets/8310677/15751633/10b393f2-28eb-11e6-822c-51be40a7934f.png)
Another tooltip will be displayed.

**Comment by Justineo** [comment]
It's the GitHub's original tooltip. Maybe we should block them when our hovercards show.

**Comment by julmot** [comment]
Absolutely.

**Comment by Justineo** [comment]
Fixed in `v0.6.4`. I'll publish it shortly, thanks for the suggestion :)
