### ISSUE TITLE
jQuery Ramdomly Hanging Firefox

### ISSUE THREAD

**Issue by louy2** [Justineo/github-hovercard#33]
For several times jQuery from hovercard has hanged my Firefox to a timeout popup which offers to debug the script. It seems random.

**Comment by Justineo** [comment]
Which version of GitHub Hovercard are you using? If you are not using the latest version, that may be the same problem as #32.

**Comment by louy2** [comment]
Thanks, I think I've met the same problem. I am using 0.6.6.

**Comment by Justineo** [comment]
@louy2 You mean the problem is still there for 0.6.6?

**Comment by louy2** [comment]
From the update time (July 31) I am pretty certain I met this on 0.6.6. But I haven't for some time, so let me close this until another case.
