### ISSUE TITLE
repo name are overlaping with slash

### ISSUE THREAD

**Issue by SSARCandy** [Justineo/github-hovercard#37]
![image](https://cloud.githubusercontent.com/assets/6803791/18809878/4dd310f4-82ba-11e6-8130-cd8a105e5753.png)

In trending page, all repo name are overlaping with the `/`, I found that in original style, all repo name will prefix with `space`, but when enabled, it didn't.

**Comment by Justineo** [comment]
It's fixed in the latest version. Thanks.
