### ISSUE TITLE
hovercard could be annoying for a ToC when viewing markdown

### ISSUE THREAD

**Issue by e-cloud** [Justineo/github-hovercard#39]
It only happens when viewing a repo readme in its home page like [this one](https://github.com/AngularClass/angular2-webpack-starter)
Is there a way to prevent hovercard to process those links

**Comment by e-cloud** [comment]
another interest of concern is i develop a outliner for markdown, when navigating from the ToC, there are too many hovercards

**Comment by Justineo** [comment]
It seems that we should prevent links inside current page from being extracted. I shall implement this soon.

**Comment by e-cloud** [comment]
great, you see it clearer

**Comment by Justineo** [comment]
Fixed in 642059699229e080ae810201bbc8ac7f84a2bf89
