### ISSUE TITLE
Add support to Github Enterprise

### ISSUE THREAD

**Issue by Psidium** [Justineo/github-hovercard#6]
Hi,
I'd like to use this plugin with Github enterprise, so I've forked and used `grep` to change `github.com` to `github.wdf.sap.corp` (our company's Github Enterprise location).

I can't make a pull request now to add a selector of github addresses, but my fork http://github.com/psidium/github-hovercard is working for me, so it's okay.

thanks for the plugin,
gabriel

**Comment by Justineo** [comment]
It should be possible to make the target domain an extension option. Maybe I'll look into this but I can't guarantee the time.

**Comment by Justineo** [comment]
I'm working on this issue but I found Chrome has bugs for extensions that require dynamically granted origin permissions. The permissions will be gone after the extension updates or the browser  restarts. See this: [Optional host permissions forgotten after browser restart](https://code.google.com/p/chromium/issues/detail?id=310815). That means I may need to request permission for all origins and inject content script according to user settings.

**Comment by Justineo** [comment]
@Psidium 

I just updated both Chrome and Firefox version, would you like to help me test it?

Just add `github.wdf.sap.corp` into Chrome extension options or Firefox add-on preference and try loading GitHub pages again.

**Comment by Psidium** [comment]
sure! Let me remote into my work machine and I'll let you know :)

2015-10-10 15:36 GMT-03:00 GU Yiling <notifications@github.com>:

> @Psidium <https://github.com/Psidium>
>
> I just updated both Chrome and Firefox version, would you like to help me
> test it?
>
> Just add github.wdf.sap.corp into Chrome extension options or Firefox
> add-on preference and try loading GitHub pages again.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Justineo/github-hovercard/issues/6#issuecomment-147115133>
> .
>



-- 
Gabriel Borges Fernandes

**Comment by Psidium** [comment]
Dunno if it's my WTS session, but when I click on options and then "add" or "save" it does nothing.

**Comment by Justineo** [comment]
What's your Chrome version? 

You can right click on the options panel and click "Inspect Element", check if there are any error in the console panel.

**Comment by Justineo** [comment]
@Psidium I updated options logic and now it should work for GitHub Enterprise. You can try out if you got time :smile:

**Comment by Justineo** [comment]
Supported in v0.3 but may need more testing.

**Comment by Psidium** [comment]
Hey! sorry for the late response, but it works like a charm in github enterprise :+1: thaankssss
