### ISSUE TITLE
Disable Hovercard on "Projects" or add a delay

### ISSUE THREAD

**Issue by julmot** [Justineo/github-hovercard#81]
When working on GitHub Projects I was annoyed by Hovercard because the tooltip appeared when moving cards around. I'd vote to disable them in the "Projects" tab or at least to add e.g. a 300ms delay to make sure the tooltip doesn't appear accidentally.

**Comment by nirodg** [comment]
I totally agree with @julmot

**Comment by ck--** [comment]
As far as I can see that is already implemented, so please close.

**Comment by Justineo** [comment]
@ck-- Actually it's not, are you saying hovercards are not working on Project pages?

**Comment by Justineo** [comment]
Added an option to disable hovercards on projects. (v1.1.0)
