### ISSUE TITLE
A slightly larger hover-card

### ISSUE THREAD

**Issue by akash-vartak** [Justineo/github-hovercard#82]
Could the hovercard size when hovering over username be made a little larger, or could someone point me to the file where this change needs to be done and I'll make that change. :+1:

**Comment by Justineo** [comment]
Would you please be more specific on this? What new design are you proposing?

**Comment by akash-vartak** [comment]
Take this for example
![screenshot from 2016-11-14 19 33 48](https://cloud.githubusercontent.com/assets/8259599/20267797/6363f68a-aaa2-11e6-8a79-77bba8a3ab35.png)

The hovercard's default size can be made a little bigger to help people read better may be a few 10px wider and taller. I reiterate that I could make the change if you could guide me to the file. :+1:

**Comment by Justineo** [comment]
Actually I intend to keep the hovercards as small as they need to be so they won't take too much space. And I'm not sure how much the extra 10px will help with readability.

Let's keep this issue open for a while to see whether there are others who share your opinion.

**Comment by Justineo** [comment]
I'm closing this for now. Thanks for the suggestion though :)

**Comment by akash-vartak** [comment]
Sure...
