### ISSUE TITLE
Not compatible with multiprocess

### ISSUE THREAD

**Issue by gluons** [Justineo/github-hovercard#84]
Mozilla's [Add-on Compatibility Reporter](https://addons.mozilla.org/en-US/firefox/addon/add-on-compatibility-reporter/) say that [GitHub Hovercard](https://addons.mozilla.org/en-US/firefox/addon/github-hovercard/) is **not compatible with multiprocess**.

<img width="794" alt="default" src="https://cloud.githubusercontent.com/assets/4688092/21299355/4f58acc6-c5cd-11e6-9342-708260382c90.PNG">

**Comment by Justineo** [comment]
It's already compatible but I forgot to declare that in package metadata. I'll fix it in the next update.

**Comment by gluons** [comment]
Fixed in **0.9.2**.

<img width="804" alt="default" src="https://cloud.githubusercontent.com/assets/4688092/21598726/47478624-d194-11e6-82e8-65657a99a8e2.PNG">
