### ISSUE TITLE
[Feature Request] Support GitHub Topics

### ISSUE THREAD

**Issue by gluons** [Justineo/github-hovercard#85]
GitHub just releases new feature called [Topics](https://github.com/blog/2309-introducing-topics).

I request for the feature to show repo's topics in hovercard.

Regards. 😊

**Comment by Justineo** [comment]
The topic information is not available from GitHub API yet AFAIK.

**Comment by gluons** [comment]
Oh! Sorry. 😳
Hope they will release API soon.

**Comment by Justineo** [comment]
Implemented via a1130dd.
