### ISSUE TITLE
Limit the number of displayed tags for commit

### ISSUE THREAD

**Issue by WOnder93** [Justineo/github-hovercard#86]
When I hover over a commit that has a lot of tags (just try it with some really old commit on https://github.com/torvalds/linux/), the popup tries to display all of them, which results in a huge popup and the important parts are often hidden behind the edge of the window.

It would be nice if there was some limit on the number of displayed tags (say, 10) with the rest replaced by an ellipsis.

**Comment by Justineo** [comment]
Thanks for the suggestion. I'll fix this in next releases.
