### ISSUE TITLE
Would like to see conversation history of issues and PRs

### ISSUE THREAD

**Issue by ck--** [Justineo/github-hovercard#87]
Currently you only display the initial comment but it would be good to see the whole history of the issue/PR in the hover card (you already allow scrolling).

PS: Many thanks for providing hovercard ... that is a great extension!

**Comment by Justineo** [comment]
I think display the whole discussion context might be too heavy for a hovercard. Not to mention that this may involve pagination and other complicated stuff. So I probably won't implement this feature. But still thanks for the suggestion.

**Comment by EMLVIRUS** [comment]
@Justineo Maybe add an option for that and set it off as default?
Sometimes I'm really found it helpful
