### ISSUE TITLE
[Setting Request] GitHub Token in add-on/extension options.

### ISSUE THREAD

**Issue by gluons** [Justineo/github-hovercard#88]
It should be great if I can set my **GitHub token** when I want. (And before limit reached) :smile: 

Could you add this in add-on/extension **options** :question:

**Comment by Justineo** [comment]
Currently the extension can work on multiple sites (GitHub Enterprise) and for various browsers, this might not be trivial because setting up options in Firefox/Safari are not as flexible as they are in Chrome/Opera/Edge. Maybe we can find a better way to setup access tokens on GitHub site(s).

**Comment by Justineo** [comment]
Implemented via c450ba3. Double click any hovercard and the token form will pop up with more detailed information.

**Comment by gluons** [comment]
Thank you. 😻
