### ISSUE TITLE
Resizable panel?

### ISSUE THREAD

**Issue by klihelp** [Justineo/github-hovercard#89]
For project's long descriptions, and if they contain images, a wider panel is better..

**Comment by EMLVIRUS** [comment]
I'm glad to see such contents

**Comment by Justineo** [comment]
Actually I don't want to encourage users to read detailed information from hovercards. The extension aims to provide quick access for general information and if users get interested they can follow the repo link to get better reading experience. So I'm not gonna support this feature request. But thank you for the suggestion anyway. 😄
