### ISSUE TITLE
Feature Request: More information on "Insert Access Token" popup

### ISSUE THREAD

**Issue by futagoza** [Justineo/github-hovercard#91]
Currently when inserting an access token, the actual webpage is darkened and an input box is displayed.

Can you please display more information here, like what permissions the token requires. I wasn't sure about the permission scopes, and just enabled all read-type scopes.

__EDIT:__ These are the scopes I enabled:

* repo
* read:org
* read:public_key
* read:repo_hook
* notifications
* user

I haven't enabled `read:gpg_key` because it's still under [Developer Preview](https://developer.github.com/changes/2016-04-04-git-signing-api-preview/)

**Comment by Justineo** [comment]
Implemented via c450ba3. Double click on any hovercard and the token form will pop up with more detailed information. Only `public_repo` and `user:follow` are required for star/unstar and follow/unfollow operations to work.
