### ISSUE TITLE
Disable/modify hovercard for Marketplace

### ISSUE THREAD

**Issue by dylmye** [Justineo/github-hovercard#97]
GitHub have released a 'marketplace' for addons. The catalogue is available [here](https://github.com/marketplace). 

Marketplace items currently show a hovercard, and obviously it doesn't work as it isn't a repor:
![example of hovercard for a marketplace item](https://user-images.githubusercontent.com/7024578/27618904-d5cd3c3e-5bb6-11e7-95f6-da02392e140b.png)

The following URL pattern could be excluded: `https://github.com/marketplace/*`  or the hovercard should be adapted for this pattern to display content about the relevant marketplace item.

P.S thanks for this amazing project! I use it a lot now.

**Comment by Justineo** [comment]
It's already been fixed in source code earlier. I'll release a new version asap. Thanks for reporting!

**Comment by Justineo** [comment]
I have published v1.1.1 in Chrome Web Store which includes this fix. Firefox/Opera versions are under moderation at the moment.
