### ISSUE TITLE
Firefox Extension is Legacy; Migrate to Web Extension

### ISSUE THREAD

**Issue by Nefari0uss** [Justineo/github-hovercard#98]
The current Firefox extension is as of now, a legacy add-on. It needs to be migrated to a Web Extension. As there is a current Chrome implementation, I am inclined to believe that it should be doable without too much work.

**Comment by Nefari0uss** [comment]
Here is a link to converting Chrome extensions into FireFox web extensions: https://developer.mozilla.org/en-US/Add-ons/WebExtensions/Porting_a_Google_Chrome_extension

**Comment by Justineo** [comment]
Thanks for the concern. 👍 

I've already been using WebExtensions for some time on my other browser extensions (and Edge version of GitHub Hovercard) so I'll migrate GitHub Hovercard before Firefox v57.

**Comment by Justineo** [comment]
I've already submitted the v1.3.2 to AMO as WebExtension. It'll be released very soon. Thanks for your support!
