### ISSUE TITLE
A bad looking when project name is too long.

### ISSUE THREAD

**Issue by simonsmh** [Justineo/github-hovercard#99]
![image](https://user-images.githubusercontent.com/9512067/28744739-dcb59ce8-7499-11e7-8a27-90b4037175ac.png)
Actually all the white area should be the same word `Magisk-Modules-Repo`.

**Comment by Justineo** [comment]
@simonsmh What happened?

**Comment by simonsmh** [comment]
Just a conflict between theme plugins...😅Sorry

GU Yiling <notifications@github.com>于2017年8月2日周三 23:02写道：

**Comment by Justineo** [comment]
OK. Thanks.
